### PR TITLE
Add support for Azure OpenAI, llama2, palm, claude2, cohere command nightly (100+ LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
- [ ] [Version](https://github.com/openedx/taxonomy-connector/blob/master/taxonomy/__init__.py) bumped
- [ ] [Changelog](https://github.com/openedx/taxonomy-connector/blob/master/CHANGELOG.rst) record added

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/taxonomy-connector/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/openedx/taxonomy-connector/actions), verify version has been pushed to [PyPI](https://pypi.org/project/taxonomy-connector/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [course-discovery](https://github.com/openedx/course-discovery) to upgrade dependencies (including taxonomy-connector)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in course-discovery will look for the latest version in PyPi.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ishaan-jaff!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by ishaan-jaff** [comment]
@saleem-latif @jajjibhai008 can I get a review on this PR ? 

happy to add docs/testing if this initial commit looks good😊

**Comment by saleem-latif** [comment]
@ishaan-jaff Can you explain the reason behind this change? Our use case of OpenAI is very simple and the official package is more than enough for our needs at this time.

**Comment by e0d** [comment]
Hi @ishaan-jaff , we need to have a valid Contributor License Agreement (CLA) in place for all contributions.  See the welcome message above for the details about how to enroll.  The process is different depending upon whether you are making this contribution as an individual or on behalf of your employer.

**Comment by e0d** [comment]
Hi @ishaan-jaff I also notice both some test failures and commit lint issues.

We use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by e0d** [comment]
> @ishaan-jaff Can you explain the reason behind this change? Our use case of OpenAI is very simple and the official package is more than enough for our needs at this time.

The use case seems pretty clear, one could choose to use a number of LLMs rather than effectively hard-coding support to OpenAI.

@ishaan-jaff seems to be one of the authors of the litellm library.  My questions are:
1. Are we confident that this library will be supported and widely adopted?
2. Are we confident that the `response` from the different LLMs will be general enough to make this library valuable?  A lot of special case handling of the response on the client side would leave us short of "supporting" these other option.

In general, I appreciate the idea of having an abstraction here, but want to know more about this specific library.

**Comment by ishaan-jaff** [comment]
@e0d thanks for the feedback and questions:
I'm the maintainer of LiteLLM

> Are we confident that this library will be supported and widely adopted?

Yes, @krrishdholakia and I work full time on litellm and are used by 40+ projects already 

> Are we confident that the response from the different LLMs will be general enough to make this library valuable? A lot of special case handling of the response on the client side would leave us short of "supporting" these other option.

@e0d can you elaborate on this / give an example ?

**Comment by ishaan-jaff** [comment]
@saleem-latif @e0d I want to make sure this PR is valuable for you. If adding new LLMs / non OpenAI LLMs is not a priority then happy to close this PR and address when the need arises

**Comment by mphilbrick211** [comment]
> @saleem-latif @e0d I want to make sure this PR is valuable for you. If adding new LLMs / non OpenAI LLMs is not a priority then happy to close this PR and address when the need arises

Hi @saleem-latif and @e0d - just flagging this for you!

**Comment by mphilbrick211** [comment]
Closing this for now, per comments above.

**Comment by openedx-webhooks** [comment]
@ishaan-jaff Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/taxonomy-connector&entry.867055334=https://github.com/openedx/taxonomy-connector/pull/178&entry.1484655318=https://github.com/ishaan-jaff&entry.752974735=2023-09-05+01:09&entry.1917517419=2023-10-03+02:13&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@ishaan-jaff Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/taxonomy-connector&entry.867055334=https://github.com/openedx/taxonomy-connector/pull/178&entry.1484655318=https://github.com/ishaan-jaff&entry.752974735=2023-09-05+01:09&entry.1917517419=2023-10-03+02:13&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
