### PR TITLE
[BB-6856] Add new management command for xblockskill tag verification

### PR DESCRIPTION
**Pull request by pkulkark**
## Description

This PR adds a new management command `finalize_xblockskill_tags` that checks the votes on tags and marks them as verified. This command will have to be run periodically - can be configured as a cron job.

## Supporting information

- OpenCraft internal task: [BB-6856](https://tasks.opencraft.com/browse/BB-6856)

## Testing Instructions
1. Install this branch in Course Discovery.
2. Ensure the host platform contains the settings values for `MIN_VOTES_FOR_SKILLS` and `RATIO_THRESHOLD_FOR_SKILLS`.
3. From within the discovery django shell, run the management command:
```
./manage.py finalize_xblockskill_tags
```
4. If the xblockskill tags have the required number of votes, it should be marked as verified.

**Reviewers**

- [ ] @navinkarkera

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pkulkark!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by pkulkark** [comment]
@HammadAhmadWaqas Sorry for the delay. Added.

**Comment by mphilbrick211** [comment]
Hi @pkulkark and @HammadAhmadWaqas - is this PR ready for review?

**Comment by pkulkark** [comment]
@mphilbrick211 Yes this is ready for review. I have rebased to latest master.

**Comment by mphilbrick211** [comment]
@pkulkark just checking back on this as it looks like some tests are failing. Would you mind re-running before review?

**Comment by pkulkark** [comment]
@mphilbrick211 Done. Rebasing to latest master fixed the failing tests.

**Comment by mphilbrick211** [comment]
Hi @moconnell1453! Flagging this for your review.

**Review by HammadAhmadWaqas — APPROVED** [review]
LGTM

**Review by moconnell1453 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@pkulkark 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/taxonomy-connector&entry.867055334=https://github.com/openedx/taxonomy-connector/pull/126&entry.1484655318=https://github.com/pkulkark&entry.752974735=2022-11-28+17:02&entry.1917517419=2023-01-13+13:20&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
